import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: "porfoliooohhhhhh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="custom-font no-scrollbar overflow-hidden">
        {children}
        <Analytics />
      </body>
    </html>
  );
}