import "./globals.css";

export const metadata = {
  title: "porfoliooohhhhhh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="custom-font">
        {children}
      </body>
    </html>
  );
}